### PR TITLE
Convert fluidsynth CLI arguments

### LINKED ISSUE #1388: MIDI files with non-ASCII characters in the filename fail to play on Windows.
### FluidSynth version
fluidsynth.exe --version
FluidSynth runtime version 2.3.6
Copyright (C) 2000-2024 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

FluidSynth executable version 2.3.6
Sample type=float

### Describe the bug
On Windows, playback failures due to non-ASCII characters in filenames occur with MIDI files, but not with SoundFont files.
MIDI files that use only ASCII characters in the filename will play correctly.

When _WIN32 macro is enabled.
fluid_is_midifile() is called twice in main() of fluidsynth.c.
The first time, u8_path is set as the argument, which is argv[i] converted by win32_ansi_to_utf8().
The second time, argv[i] is set as the argument without being converted.
This difference is a bit concerning.

Thank you.

### PR DESCRIPTION
**Pull request by pedrolcl**
Closes #1388

### CODE REVIEW

**Review by derselbst — APPROVED** [review]
I like that solution, thanks!

File: src/fluidsynth.c [hunk 1]
```diff
@@ -403,11 +356,40 @@ int main(int argc, char **argv)
...
+    {
+        fprintf(stderr, "Out of memory\n");
+        goto cleanup;
+    }
+    else
+    {
+        for (i = 0; i < argc; ++i)
+        {
+            int u8_count = 0;
+            if (1 > (u8_count = WideCharToMultiByte(CP_UTF8, WC_ERR_INVALID_CHARS, wargv[i], -1, NULL, 0, NULL, NULL)))
```
Comment (derselbst) [inline src/fluidsynth.c:376]: @pedrolcl We have a minor oversight: `WC_ERR_INVALID_CHARS` is not available for WindowsXP, causing the CI to fail:
https://dev.azure.com/tommbrt/tommbrt/_build/results?buildId=10875&view=logs&j=ae601b3d-8756-52a4-4bcc-59c4d24c3f8c&t=1e42d489-b2c6-5e77-903e-6d797975357c&l=653

JJC needs WindowsXP compatibility. I haven't seen this earlier, because the build failed due to an issue in libinstpatch related to your bump of libsndfile min version: https://github.com/swami/libinstpatch/pull/78

Comment (pedrolcl) [reply src/fluidsynth.c:376]: Then, the only option is to replace the WC_ERR_INVALID_CHARS flag by 0.

Comment (derselbst) [reply src/fluidsynth.c:376]: Would something like

```c
#ifndef WC_ERR_INVALID_CHARS
#define WC_ERR_INVALID_CHARS 0
#endif
```

make sense, so that at least on modern Windows it reports a proper error?
